books/api/urls.py
from django.conf.urls import url

from .views import BookViewSet

urlpatterns = [
	url(r'^$', BookViewSet.as_view(), name='book_list'),
]

books/urls.py
from django.conf.urls import url

from .views import BookListView, BookDetailView, bookborrow, SuggestBookView

urlpatterns = [
	url(r'^$', BookListView.as_view(), name='list'),
	url(r'^(?P<id>\d+)/$', BookDetailView.as_view(), name='detail'),
	url(r'^(?P<id>\d+)/borrow/$', bookborrow, name='borrow'),
	url(r'^suggestbook/$', SuggestBookView.as_view(), name='suggestbook'),
]

library/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import homepage, contactus
from users.views import (login_view, register_view, logout_view, profile)

urlpatterns = [
    url(r'^$', homepage, name='index'),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^u/', include('users.urls', namespace="users")),
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls', namespace='books')) ,
    url(r'^staff/', include('staff.urls', namespace='staff')),
    url(r'^contact/', contactus, name='contact'),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),

    # API views
    #url(r'^api/book/', include('books.api.urls', namespace='book-api')),
    #url(r'^api/users/', include('users.api.urls', namespace='users-api')),
]

books/models.py
import datetime

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.shortcuts import get_object_or_404
from django.utils.text import slugify

# Create your models here.

ALLOWED_IMG_TYPE = ['png', 'jpg', 'bmp']


class Tags(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name_plural = "Tags"


class Book(models.Model):
	book_name = models.CharField(max_length=200)
	slug = models.CharField(max_length=255, unique=True)
	author_name = models.CharField(max_length=200)
	isbn = models.IntegerField(verbose_name='ISBN', unique=True)
	status = models.BooleanField(default=True)
	description = models.TextField(null=True, blank=True)
	tags = models.ManyToManyField(Tags, blank=True)
	image = models.ImageField(
			null=True, 
			blank=True, 
			width_field="width_field", 
			height_field="height_field")	
	height_field = models.IntegerField(default=300)
	width_field = models.IntegerField(default=250)
	created = models.DateField(auto_now_add=True)
	number_of_pages = models.IntegerField()
	publish_date = models.DateField()
	publish_place = models.CharField(max_length=200)
	edition = models.CharField(max_length=100)
	borrower = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='books', blank=True, null=True)


	def __str__(self):
		return self.book_name

	def __unicode__(self):
		return self.book_name

	def get_tags(self):
		tags = ','.join([tag.name for tag in self.tags.all()])
		return tags

	def get_absolute_url(self):
		return reverse("books:detail", kwargs={"id" : self.id})

	class Meta:
		ordering = ["-created"]


def create_slug(instance, new_slug=None):
	book_name_lowered = instance.book_name.lower()
	slug = slugify(book_name_lowered)
	if new_slug is not None:
		slug = new_slug
	qs = Book.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s-%s" %(slug, qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)
	

pre_save.connect(pre_save_post_receiver, sender=Book)


class BookBorrow(models.Model):
	date_borrow_start = models.DateField()
	date_borrow_end = models.DateField(blank=True, null=True)
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	note = models.TextField(blank=True, null=True)
	book_borrowed = models.ForeignKey(Book)

	def __str__(self):
		return str(self.date_borrow_start)

	def __unicode__(self):
		return self.date_borrow_start


def post_save_post_receiver(sender, instance, *args, **kwargs):
	book_id = instance.book_borrowed.id
	book = get_object_or_404(Book, id=book_id)
	book.status = False
	book.borrower = instance.user
	book.save()

post_save.connect(post_save_post_receiver, sender=BookBorrow)


class BookSuggestion(models.Model):
	book_name = models.CharField(max_length=200)
	isbn = models.IntegerField(blank=True, null=True)
	author_name = models.CharField(max_length=200, blank=True, null=True)
	comment = models.TextField(blank=True, null=True)
	created = models.DateField(auto_now_add=True)

	def __str__(self):
		return self.book_name

	def __unicode__(self):
		return self.book_name

	class Meta:
		ordering = ['-created']

books/forms.py
from django import forms

from .models import Book, BookBorrow, BookSuggestion, Tags


class BookForm(forms.ModelForm):
	class Meta:
		model = Book
		fields = ["book_name", "author_name", "isbn", "publish_date", "publish_place", "tags", 
				 "description", "number_of_pages", "edition"]


class BookBorrowForm(forms.ModelForm):
	date_borrow_start = forms.DateField(widget=forms.DateInput(attrs={'id': 'datepicker', 'placeholder': 'ex: 2016-02-22'}))
	date_borrow_end = forms.DateField(widget=forms.DateInput(attrs={'id': 'datepicker', 'placeholder': 'ex: 2016-02-29'}))

	# def clean(self, *args, **kwargs):
		# date_borrow_start = self.cleaned_data.get("date_borrow_start")
		# date_borrow_end = self.cleaned_data.get("date_borrow_end")

		# if date_borrow_end < date_borrow_start:
		# 	raise forms.ValidationError("return date cant be before borrow date")

	class Meta:
		model = BookBorrow
		fields = ["date_borrow_start", "date_borrow_end", "note",]


class SuggestBookForm(forms.ModelForm):
	class Meta:
		model = BookSuggestion
		fields = ["book_name", "isbn", "author_name", "comment"]


class TagsForm(forms.ModelForm):
	class Meta:
		model = Tags
		fields = ["name"]

books/api/views.py
from rest_framework.generics import ListAPIView

from books.models import Book
from .serializers import BookSerializer

class BookViewSet(ListAPIView):
	queryset = Book.objects.all()
	serializer_class = BookSerializer

books/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.urlresolvers import reverse, reverse_lazy
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, ListView
from django.views.generic.edit import FormView
from stronghold.views import StrongholdPublicMixin

from .forms import BookBorrowForm, BookForm, SuggestBookForm
from .models import Book, BookBorrow, Tags


"""

"""
class BookListView(StrongholdPublicMixin, ListView):
	def get(self, request):
		books = Book.objects.all()
		tags = Tags.objects.all()
		query = request.GET.get("q")
		if query:
			books = books.filter(
			Q(book_name__icontains=query)|
			Q(author_name__icontains=query)|
			Q(tags__name__icontains=query)
			).distinct()

		paginator = Paginator(books, 3) # Show 3 books per page

		page = request.GET.get('page')
		try:
			books = paginator.page(page)
		except PageNotAnInteger:
		# If page is not an integer, deliver first page.
			books = paginator.page(1)
		except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
			books = paginator.page(paginator.num_pages)
		
		context = {
			'books' : books,
			'tags' : tags
			}
		return render(request, 'book_list.html', context)


"""

"""
class BookDetailView(StrongholdPublicMixin, DetailView):
	model = Book
	pk_url_kwarg = 'id'
	template_name = "book_detail.html"
	form = BookBorrowForm()

	def get_context_data(self, **kwargs):
		# Call the base implementation first to get a context
		context = super(BookDetailView, self).get_context_data(**kwargs)
		# Add in the publisher
		context['form'] = self.form
		return context

"""

"""
def bookborrow(request, id):
	book_id = get_object_or_404(Book, id=id)
	form = BookBorrowForm(request.POST or None)
	if request.method == "POST":
		if form.is_valid():
			date_borrow_start = form.cleaned_data.get("date_borrow_start")
			date_borrow_end = form.cleaned_data.get("date_borrow_end")
			instance = form.save(commit=False)
			instance.book_borrowed = book_id
			instance.user = User.objects.get(id=request.user.id)
			instance.save()
		return redirect(reverse('books:detail', kwargs={'id': book_id.id}))
	context = {
		'form' : form
	}
	return render(request, 'book_borrow.html', context)


"""

"""
class SuggestBookView(StrongholdPublicMixin,SuccessMessageMixin, FormView):
	template_name = 'suggestbook.html'
	form_class = SuggestBookForm
	success_url = reverse_lazy('index')
	success_message = "Thank you!"

	def form_valid(self, form):
		# This method is called when valid form data has been POSTed.
		# It should return an HttpResponse.
		form.save()
		return super(SuggestBookView, self).form_valid(form)

books/templates/add_book.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
	<form action="" method="POST">
		{% csrf_token %}
	{{ form|crispy }}
	<input type="submit" value="create" class="btn btn-defautl">
	</form>
	</div>
{% endblock %}

books/templates/book_borrow.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="container">
    <h1 class="page-header">Confirm Borrowing
    </h1>

    <div class="col s12 m6">
        <form action="" method="POST">
            {% csrf_token %} {{ form|crispy }}
            <input type="submit" value="submit" class="btn">
        </form>
    </div>
</div>
{% endblock %}

books/templates/book_detail.html
{% extends 'base.html' %} {% load staticfiles %} {% load ratings %} {% load crispy_forms_tags %} {% block custom_content %}
<div id="fb-root"></div>
<script>
(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.7";
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>
{% endblock %} {% block content %}
<div class="container">
    <h1 class="page-header">Book Details
    </h1>
    <div class="row">
        <div class="thumbnail">
            <img class="responsive-img" src="{% static 'img/bookdetail.jpg' %}">
            <div class="caption-full">
                <h4>{{ book.book_name }}</h4>
                <p><b>author:</b> {{ book.author_name }}</p>
                <p>{{ book.description }}</p>
                <p><b>ISBN:</b> {{ book.isbn }}</p>
                <p><b>status:</b> {% if not book.status %}
                    <span class="label label-danger">Taken</span> {% else %}
                    <span class="label label-success">Available</span> {% endif %}</p>
                <p><b>publish date:</b> {{ book.publish_date }}</p>
                <p><b>publish place:</b> {{ book.publish_place }}</p>
                <p><b>edition</b> {{ book.edition }}</p>
                <p><b>tags: </b> {{ book.get_tags }}</p>
                {% if user.is_authenticated %} {% if book.borrower == request.user %}
                <div class="card red" role="alert">
                    <p class="center white-text">you already borrowed this book!</p>
                </div>
                {% else %}
                <div class="row">
                    <div class="col s6">
                        <a class="btn {% if not book.status %}disabled {% endif %}" href="{% url 'books:borrow' book.id %}">Borrow </a>
                    </div>
                </div>
                {% endif %} {% else %}
                <div class="row ">
                    <div class="borrow-btn">
                        <button class="btn"><a href="{% url 'login' %}">login to borrow this book </a></button>
                    </div>
                </div>
                {% endif %}
                <br/>
                
                <div class="ratings">
                    {% ratings object %}
                </div>
            </div>
            <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-width="100%" data-numposts="5">
            </div>
        </div>
    </div>
</div>
{% endblock %}

books/templates/book_list.html
{% extends 'base.html' %} {% block content %}
<div class="container">
    <h1 class="page-header">Book List</h1>
</div>
<div class="row">
    {% include 'sidebar.html' %}
    <div class="col s9">
        <div class="row">
            {% for book in books %}
            <div class="col s12 m4">
                <div class="card">
                    <div class="card-image">
                        {% if not book.image %}
                        <img src="http://placehold.it/250x300" class="img-responsive" alt="book cover"> {% else %}
                        <img src="{{ book.image.url }}" class="img-responsive" alt="book cover"> {% endif %}
                        <span class="card-title">{{ book.book_name }}</span>
                    </div>
                    <div class="card-content">
                        <p>{{ book.description|truncatechars:60 }}</p>
                    </div>
                    <div class="card-action">
                        <a href="{{ book.get_absolute_url }}">check</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="pagination">
            <ul class="pager">
                {% if books.has_previous %}
                <li class="previous"><a href="?page={{ books.previous_page_number }}">previous</a></li>
                {% endif %} {% if books.has_next %}
                <li class="next"><a href="?page={{ books.next_page_number }}">next</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

books/templates/confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
  {% csrf_token %}
    Are you sure you want to delete {{object}} ?
    <input type="submit" value="Submit" class="btn btn-danger" />
</form>
{% endblock %}

books/templates/suggestbook.html
{% extends 'base.html' %}{% load material_form %}
{% block content %}
<div class="container">
    <h1>Suggest a Book</h1>

<div class="col s12">
    <form action="" method="POST">
        {% csrf_token %} {% form form=form %} {% endform %}
        <input type="submit" value="submit" class="btn blue">
    </form>
    <br>
</div>
</div>
{% endblock %}