books/urls.py
from django.conf.urls import url

from .views import BookListView, BookDetailView, bookborrow, SuggestBookView

urlpatterns = [
	url(r'^$', BookListView.as_view(), name='list'),
	url(r'^(?P<id>\d+)/$', BookDetailView.as_view(), name='detail'),
	url(r'^(?P<id>\d+)/borrow/$', bookborrow, name='borrow'),
	url(r'^suggestbook/$', SuggestBookView.as_view(), name='suggestbook'),
]

library/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import homepage, contactus
from users.views import (login_view, register_view, logout_view, profile)

urlpatterns = [
    url(r'^$', homepage, name='index'),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^u/', include('users.urls', namespace="users")),
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls', namespace='books')) ,
    url(r'^staff/', include('staff.urls', namespace='staff')),
    url(r'^contact/', contactus, name='contact'),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),

    # API views
    #url(r'^api/book/', include('books.api.urls', namespace='book-api')),
    #url(r'^api/users/', include('users.api.urls', namespace='users-api')),
]

staff/urls.py
from django.conf.urls import url

from .views import (BookListView, AddBookView, EditBookView, 
					DeleteBookView, UserListView, DeleteUserView, HomePageView, releasebook, Suggestions,
					Tagslist, AddTagView, EditTagView, DeleteTagView)

urlpatterns = [
	#homepage for staff
	url(r'^$', HomePageView.as_view(), name='homepage'),
	#books urls for staffs
	url(r'^books/$', BookListView.as_view(), name='book_list'),
	url(r'^books/add/$', AddBookView.as_view(), name='create'),
	url(r'^books/(?P<id>\d+)/edit/$', EditBookView.as_view(), name='update'),
	url(r'^books/(?P<id>\d+)/delete/$', DeleteBookView.as_view(), name='delete'),
	url(r'^books/(?P<id>\d+)/release/$', releasebook, name='release'),
	#users urls for staffs
	url(r'^users/$', UserListView.as_view(), name='user_list' ),
	url(r'^users/(?P<id>\d+)/delete/$', DeleteUserView.as_view(), name='delete_user'),
	url(r'^suggestions/$', Suggestions.as_view(), name='suggestions'),
	#tags url for staffs
	url(r'^tags/$', Tagslist.as_view(), name='tagslist'),
	url(r'^tags/add/$', AddTagView.as_view(), name='add_tag'),
	url(r'^tags/update/(?P<id>\d+)/$', EditTagView.as_view(), name='update_tag'),
	url(r'^tags/(?P<id>\d+)/delete/$', DeleteTagView.as_view(), name='delete_tag')
]

users/urls.py
from django.conf.urls import url

from .views import  profile, update
from django.contrib.auth.views import password_change

urlpatterns = [
	url(r'^profile/resetpassword/$', password_change, name='reset_password'),
    url(r'^profile/(?P<id>\d+)/$', profile, name='profile'),
    url(r'^update_profile/(?P<id>\d+)/$', update, name='update'),
]

staff/models.py
from django.db import models

# Create your models here.

staff/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import DetailView, ListView, View
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from stronghold.views import StrongholdPublicMixin

from books.forms import BookBorrowForm, BookForm, TagsForm
from books.models import Book, BookSuggestion, Tags


class HomePageView(TemplateView):
	def get(self, request, *args, **kwargs):
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		else:
			return render(request, 'staff_homepage.html')


class BookListView(ListView):
	def get(self, request):
		books = Book.objects.all()
		query = request.GET.get("q")
		if query:
			books = books.filter(
			Q(book_name__icontains=query)|
			Q(author_name__icontains=query)|
			Q(tags__name__icontains=query)
			).distinct()

		paginator = Paginator(books, 10) # Show 25 contacts per page

		page = request.GET.get('page')
		try:
			books = paginator.page(page)
		except PageNotAnInteger:
		# If page is not an integer, deliver first page.
			books = paginator.page(1)
		except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
			books = paginator.page(paginator.num_pages)
		
		context = {
			'books' : books,
			}
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		else:
			return render(request, 'staff_book_list.html', context)


class AddBookView(SuccessMessageMixin, CreateView):
	
	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		return super(AddBookView, self).dispatch(request, *args, **kwargs)

	form_class = BookForm
	model = Book
	template_name = "staff_add_form.html"
	success_message = "%(book_name)s was created successfully"

	def get_context_data(self, **kwargs):
		context = super(AddBookView, self).get_context_data(**kwargs)
		context.update({'pagename': "Add new Book"})
		return context

	def get_success_url(self):
		return reverse('staff:book_list')


class EditBookView(SuccessMessageMixin, UpdateView):

	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		return super(EditBookView, self).dispatch(request, *args, **kwargs)

	form_class = BookForm
	model = Book
	pk_url_kwarg = 'id'
	template_name = "staff_add_form.html"
	success_message = "%(book_name)s was updated successfully"

	def get_context_data(self, **kwargs):
		context = super(EditBookView, self).get_context_data(**kwargs)
		context.update({'pagename': "Update Book"})
		return context

	def get_success_url(self):
		return reverse('staff:book_list')


class DeleteBookView(SuccessMessageMixin, View):
	
	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		return super(DeleteBookView, self).dispatch(request, *args, **kwargs)
		
	def delete(self, request, id):
    # delete an object and send a confirmation response
	    Book.objects.get(pk = id).delete()
	    return HttpResponse('deleted!')


# def deleteBook(request, id):
# 	if request.method == "DELETE":
# 		Book.objects.get(pk=request.DELETE['pk']).delete()
# 		return HttpResponse('deleted!', content_type="text/plain")
# 	return HttpResponse('not working!')


"""
delete user from the book isntance and change its status
args = id of the user
return = redirect
"""
def releasebook(request, id):
	if not request.user.is_staff:
			return render(request, 'no_access.html')
	else:
		book = get_object_or_404(Book, id=id)
		if request.method == "POST":
			book.status = True
			book.borrower = None
			book.save()
		messages.success(request, 'Book released.')
		return redirect(reverse('staff:book_list'))


"""
args = None
return = list of all the users including the staff
"""
class UserListView(ListView):
	def get(self, request):
		users = User.objects.all()
		context = {
			'users' : users
		}
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		else:
			return render(request, 'staff_user_list.html', context)


"""
delete a specific user from the database
args = id of the user
return = refresh
"""
class DeleteUserView(SuccessMessageMixin, View):
	
	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		return super(DeleteUserView, self).dispatch(request, *args, **kwargs)
		
	def delete(self, request, id):
    # delete an object and send a confirmation response
	    user = User.objects.get(pk = id)
	    if not user.is_staff:
	    	user.delete()
	    return HttpResponse('deleted!')

"""
list all the suggestions from the database 
args = None
return = list
"""
class Suggestions(ListView):
	def get(self, request):
		suggestions = BookSuggestion.objects.all()
		context = {
			'suggestions' : suggestions
		}
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		else:
			return render(request, 'suggestions.html', context)


"""
return list of the tags from the database 
args = None
return = list
"""
class Tagslist(StrongholdPublicMixin, ListView):
	def get(self, request):
		tags = Tags.objects.all()
		context = {
			'tags' : tags,
		}
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		else:
			return render(request, 'staff_tags_list.html', context)


"""
create a new tag and store in the database
args = data from the form
return = redirect
"""
class AddTagView(SuccessMessageMixin, CreateView):
	
	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		return super(AddTagView, self).dispatch(request, *args, **kwargs)
	
	form_class = TagsForm
	model = Tags
	template_name = "staff_add_form.html"
	success_message = "%(name)s was created successfully"

	def get_context_data(self, **kwargs):
		context = super(AddTagView, self).get_context_data(**kwargs)
		context.update({'pagename': "Add new Tag"})
		return context

	def get_success_url(self):
		return reverse('staff:tagslist')


"""
modify a specific tag
args = id
return = redirect
"""
class EditTagView(SuccessMessageMixin, UpdateView):
	
	def dispatch(self, request, *args, **kwargs):
		if not request.user.is_staff:
			return render(request, 'no_access.html')
		return super(EditTagView, self).dispatch(request, *args, **kwargs)
	
	form_class = TagsForm
	model = Tags
	pk_url_kwarg = 'id'
	template_name = "staff_add_form.html"
	success_message = "%(name)s was updated successfully"

	def get_context_data(self, **kwargs):
		context = super(EditTagView, self).get_context_data(**kwargs)
		context.update({'pagename': "Update Tag"})
		return context

	def get_success_url(self):
		return reverse('staff:tagslist')


"""
delete a specific tag
args = id
return = redirect
"""
class DeleteTagView(SuccessMessageMixin, DeleteView):
	
	def delete(self, request, id):
    # delete an object and send a confirmation response
	    Tags.objects.get(pk = id).delete()
	    return HttpResponse('deleted!')
	# model = Tags
	# pk_url_kwarg = 'id'
	# template_name = "confirm_delete.html"
	# success_message = "item was deleted successfully"

	# def get_success_url(self):
	# 	return reverse('staff:tagslist')

staff/templates/confirm_delete.html
{% extends 'staff_base.html' %}
{% block content %}

	 {% include 'staff_navbar.html' %}
            <!-- /.navbar-collapse -->
        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Confirm delete</h1>
                    </div>
						<form method="post">
						  {% csrf_token %}
						    Are you sure you want to delete {{object}} ?
						    <input type="submit" value="Submit" class="btn btn-danger" />
						</form>
					</div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->
{% endblock %}

staff/templates/staff_add_form.html
{% extends 'staff_base.html' %}      
{% load crispy_forms_tags %} 

{% block content %} {% include 'staff_navbar.html' %}
<!-- /.navbar-collapse -->
<div id="page-wrapper">
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-sm-12">
                <h1 class="container">{{ pagename }}</h1>
            </div>
        </div>
        <div class="container col-md-6">
            <form action="" method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
               {{ form|crispy }}
                <input type="submit" value="submit" class="btn btn-primary">
            </form>
        </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /#page-wrapper -->
{% endblock %}

staff/templates/staff_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Dashboard</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">

    <!-- Custom CSS -->
     <link href="{% static 'css/sb-admin.css' %}" rel="stylesheet"> 
    
    <!-- SweetAlert CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/sweetalert.css' %}">

    <!-- Custom Fonts -->
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    {% block css %}{% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">
    {% if messages %}
            {% for message in messages %}
            <div class="alert alert-success" role="alert">
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
            </div>
            {% endfor %}
    {% endif %}
    {% block content %}{% endblock %}

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script   src="{% static 'js/jquery-2.2.4.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript 
    <script src="{% static 'js/bootstrap.min.js' %}"></script>-->
    <script type="text/javascript" src="{% static 'js/sweetalert.min.js' %}" ></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/ajax_functions.js' %}"></script>
    {% block js %}{% endblock %}
</body>
</html>

staff/templates/staff_book_list.html
{% extends 'staff_base.html' %} {% load static %} 

{% block content %} 

{% include 'staff_navbar.html' %}
<!-- /.navbar-collapse -->
<div id="page-wrapper">
    <div class="container-fluid">
        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Book List</h1>
            </div>
            <div class="col-md-3">
                <form action="">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Search for..." 
                        value="{{ request.GET.q }}">
                        <span class="input-group-btn">
        <button class="btn btn-default" type="submit">Go!</button>
      </span>
                </form>
                </div>
                <!-- /input-group -->
            </div>
            <table class="table table-hover table-striped">
                <thead>
                    <tr>
                        <th>book name</th>
                        <th>author name</th>
                        <th>status</th>
                        <th>borrower</th>
                    </tr>
                </thead>
                <tbody>
                    {% for book in books %}
                    <tr id="books-{{book.id}}">
                        <td>{{book.book_name}}</td>
                        <td>{{book.author_name}}</td>
                        <td>{% if book.status %}
                            <span class="label label-success">Available</span> {% else %}
                            <span class="label label-danger">Taken</span> {% endif%}</td>
                        <td>{% if book.borrower %} <a href="{% url 'users:profile' book.borrower.id %}">
                        {{book.borrower}}</a> {% else %} -- {% endif %}
                        </td>
                        <td><a href="{% url 'staff:update' book.id %}" class="btn btn-warning">update</a></td>
                        <td><button onclick="delete_book({{ book.id }}, 'books')" 
                            {% if not request.user.is_superuser %} disabled="true" {% endif %}
                            class="btn btn-danger">delete</button></td>
                        <td>
                            <form action="{% url 'staff:release' book.id %}" method="POST">{% csrf_token %}
                                <input type="submit" {% if book.status %} disabled="true" {% endif %} value="release" class="btn btn-info">
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
    <div class="pagination col-sm-9">
        <ul class="pager">
            {% if books.has_previous %}
            <li class="previous"><a href="?page={{ books.previous_page_number }}">previous</a></li>
            {% endif %} {% if books.has_next %}
            <li class="next pull-righ"><a href="?page={{ books.next_page_number }}">next</a></li>
            {% endif %}
        </ul>
    </div>
</div>

{% endblock %}

staff/templates/staff_homepage.html
{% extends 'staff_base.html' %}
{% block content %}
    
     {% include 'staff_navbar.html' %}
            <!-- /.navbar-collapse -->
        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Homepage
                        </h1>
                        <div class="row">
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-comments fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">26</div>
                                        <div>New Comments!</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-green">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-tasks fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">12</div>
                                        <div>New Tasks!</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-yellow">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-shopping-cart fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">124</div>
                                        <div>New Orders!</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <div class="panel panel-red">
                            <div class="panel-heading">
                                <div class="row">
                                    <div class="col-xs-3">
                                        <i class="fa fa-support fa-5x"></i>
                                    </div>
                                    <div class="col-xs-9 text-right">
                                        <div class="huge">13</div>
                                        <div>Support Tickets!</div>
                                    </div>
                                </div>
                            </div>
                            <a href="#">
                                <div class="panel-footer">
                                    <span class="pull-left">View Details</span>
                                    <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                    <div class="clearfix"></div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

{% endblock %}

staff/templates/staff_navbar.html
<!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Dashboard</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
               <li><a href="{% url 'users:profile' request.user.pk %}">profile</a></li>
               <li><a href="{% url 'logout' %}">logout</a></li>
               <li><a href="{% url 'index' %}">home</a></li>
               
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li>
                        <a href="{% url 'staff:homepage' %}"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'staff:user_list' %}"><i class="fa fa-fw fa-users"></i> Users</a>
                    </li>
                    <li>
                        <a href="{% url 'staff:book_list' %}"><i class="fa fa-fw fa-book"></i> Books</a>
                    </li>
                    <li>
                        <a href="{% url 'staff:create' %}"><i class="fa fa-fw fa-plus"></i> Add new book</a>
                    </li>
                    <li>
                        <a href="{% url 'staff:tagslist' %}"><i class="fa fa-fw fa-gear"></i> Tags</a>
                    </li>
                    <li>
                        <a href="{% url 'staff:add_tag' %}"><i class="fa fa-fw fa-plus"></i> Add new Tag</a>
                    </li>
                    <li>
                        <a href="{% url 'staff:suggestions' %}"><i class="fa fa-fw fa-gear"></i> Suggestions</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

staff/templates/staff_tags_list.html
{% extends 'staff_base.html' %}

{% block content %}
        {% include 'staff_navbar.html' %}
            <!-- /.navbar-collapse -->
        <div id="page-wrapper">

            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">tags List</h1>
                    </div>
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                            <th>name</th>
                            </tr>
                        </thead>
                        <tbody>
                  {% for tag in tags %}
                    <tr id="tags-{{tag.pk}}">
                        <td>{{tag.name}}</td>
                        <td><a href="{% url 'staff:update_tag' tag.id %}" 
                            class="btn btn-warning">update</a></td>
                            <td>
                        <button onclick="delete_book({{ tag.id }}, 'tags')" 
                            {% if not request.user.is_superuser %} disabled="true" {% endif %}
                            class="btn btn-danger">delete</button></td>
                    </tr>
                  {% endfor %}
                  </tbody>
                  </table>
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

{% endblock %}

staff/templates/staff_user_list.html
{% extends 'staff_base.html' %}

{% block content %}
        {% include 'staff_navbar.html' %}
            <!-- /.navbar-collapse -->
        <div id="page-wrapper">

            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">Users List</h1>
                    </div>
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                            <th>first name</th>
                            <th>last name</th>
                            <th>date joined</th>
                            <th>email</th>
                            <th>type</th>
                            <th>books borrowed</th>
                            </tr>
                        </thead>
                        <tbody>
                  {% for user in users %}
                    <tr id="users-{{user.id}}">
                        <td>{{user.first_name}}</td>
                        <td>{{user.last_name}}</td>
                        <td>{{user.date_joined}}</td>
                        <td>{{user.email}}</td>
                        <td>
                        {% if user.is_staff or user.is_superuser %} staff {% else %} normal user {% endif %}
                        </td>
                        <td>{% if user.books.all %}
                            {% for book in user.books.all %}
                           <p> <a href="{% url 'books:detail' book.id %}">{{book.book_name}}</a> </p>
                            {% endfor %}
                            {% else %}
                            <p> user didn't borrow any book </p>
                            {% endif %}
                        </td>
                        <td><button onclick="delete_book({{user.id}},'users')" 
                            {% if not request.user.is_superuser %} 
                            disabled="true" {% endif %}
                            class="btn btn-danger">delete</button></td>
                        <td>
                       
                    </tr>
                  {% endfor %}
                  </tbody>
                  </table>
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

{% endblock %}

staff/templates/suggestions.html
{% extends 'staff_base.html' %}

{% block content %}

{% include 'staff_navbar.html' %}
<div class="col-lg-12">
    <h1 class="page-header">Suggestions List</h1>
</div>
<div class="container col-md-12 col-lg-12">
{% for item in suggestions %}
	<div class="panel panel-default">
	  <div class="panel-heading"><b>{{ item.book_name }}</b> | {{ item.created }}</div>
	  <div class="panel-body">
	    <p>isbn: {% if item.isbn %} {{ item.isbn }} {% else %} N/A {% endif %}</p>
		<p>author name: {% if item.author_name %} {{ item.author_name }} {% else %} N/A {% endif %}</p>
		<p>comment: {% if item.comment %} {{ item.comment }} {% else %} N/A {% endif %}</p>
	  </div>
	</div>
{% endfor %}
</div>
{% endblock %}

staff/templates/tagslist.html
{% extends 'staff_base.html' %}

{% block content %}
        {% include 'staff_navbar.html' %}
            <!-- /.navbar-collapse -->
        <div id="page-wrapper">

            <div class="container-fluid">
                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">tags List</h1>
                    </div>
                    <table class="table table-hover table-striped">
                        <thead>
                            <tr>
                            <th>name</th>
                            </tr>
                        </thead>
                        <tbody>
                  {% for tag in tags %}
                    <tr>
                        <td>{{tag.name}}</td>
                        <td><a href="{% url 'staff:update_tag' tag.id %}" 
                            class="btn btn-warning">update</a></td>
                        <td><a href="{% url 'staff:delete_tag' tag.id %}" 
                            class="btn btn-danger">delete</a></td>
                    </tr>
                  {% endfor %}
                  </tbody>
                  </table>
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

{% endblock %}