books/urls.py
from django.conf.urls import url

from .views import BookListView, BookDetailView, bookborrow, SuggestBookView

urlpatterns = [
	url(r'^$', BookListView.as_view(), name='list'),
	url(r'^(?P<id>\d+)/$', BookDetailView.as_view(), name='detail'),
	url(r'^(?P<id>\d+)/borrow/$', bookborrow, name='borrow'),
	url(r'^suggestbook/$', SuggestBookView.as_view(), name='suggestbook'),
]

library/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import homepage, contactus
from users.views import (login_view, register_view, logout_view, profile)

urlpatterns = [
    url(r'^$', homepage, name='index'),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^u/', include('users.urls', namespace="users")),
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls', namespace='books')) ,
    url(r'^staff/', include('staff.urls', namespace='staff')),
    url(r'^contact/', contactus, name='contact'),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),

    # API views
    #url(r'^api/book/', include('books.api.urls', namespace='book-api')),
    #url(r'^api/users/', include('users.api.urls', namespace='users-api')),
]

staff/urls.py
from django.conf.urls import url

from .views import (BookListView, AddBookView, EditBookView, 
					DeleteBookView, UserListView, DeleteUserView, HomePageView, releasebook, Suggestions,
					Tagslist, AddTagView, EditTagView, DeleteTagView)

urlpatterns = [
	#homepage for staff
	url(r'^$', HomePageView.as_view(), name='homepage'),
	#books urls for staffs
	url(r'^books/$', BookListView.as_view(), name='book_list'),
	url(r'^books/add/$', AddBookView.as_view(), name='create'),
	url(r'^books/(?P<id>\d+)/edit/$', EditBookView.as_view(), name='update'),
	url(r'^books/(?P<id>\d+)/delete/$', DeleteBookView.as_view(), name='delete'),
	url(r'^books/(?P<id>\d+)/release/$', releasebook, name='release'),
	#users urls for staffs
	url(r'^users/$', UserListView.as_view(), name='user_list' ),
	url(r'^users/(?P<id>\d+)/delete/$', DeleteUserView.as_view(), name='delete_user'),
	url(r'^suggestions/$', Suggestions.as_view(), name='suggestions'),
	#tags url for staffs
	url(r'^tags/$', Tagslist.as_view(), name='tagslist'),
	url(r'^tags/add/$', AddTagView.as_view(), name='add_tag'),
	url(r'^tags/update/(?P<id>\d+)/$', EditTagView.as_view(), name='update_tag'),
	url(r'^tags/(?P<id>\d+)/delete/$', DeleteTagView.as_view(), name='delete_tag')
]

users/urls.py
from django.conf.urls import url

from .views import  profile, update
from django.contrib.auth.views import password_change

urlpatterns = [
	url(r'^profile/resetpassword/$', password_change, name='reset_password'),
    url(r'^profile/(?P<id>\d+)/$', profile, name='profile'),
    url(r'^update_profile/(?P<id>\d+)/$', update, name='update'),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Book lending library">
    <meta name="author" content="REV">

    <title>Library</title>

    <!-- CSS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="{% static 'css/materialize.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block extra_css %}{% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="base_template">
{% block custom_content %}{% endblock %}

{% include 'navbar.html' %}
<main>
    <!-- Page Content -->

        {% block content %}{% endblock %}
    <!-- end Page Content -->
</main>
{% include 'footer.html' %}

<!--  Scripts-->
  <script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="container">
                <h1 class="page-header">Contact Us</h1>
    </div>
        <!-- Content Row -->
        <div class="row">
            <!-- Map Column -->
            <div>
                <!-- Embedded Google Map -->
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d10504.657443982273!2d2.3755322074968133!3d48.83600351564694!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e6723cff6df901%3A0x28f6e235ce38e199!2z2YXZg9iq2KjYqSDZgdix2YbYs9inINin2YTZiNi32YbZitip!5e0!3m2!1sar!2stn!4v1472831035363" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </div>
</div>
<div class="container">
    <div class="row">
        <div class="col m10 offset-m1 s12">
            <h2 class="center-align">Contact Form</h2>
            <div class="row">
                <form class="col s12">
                    <div class="row">
                        <div class="input-field col m6 s12">
                            <input id="first_name" type="text" class="validate">
                            <label for="first_name">First Name</label>
                        </div>
                        <div class="input-field col m6 s12">
                            <input id="last_name" type="text" class="validate">
                            <label for="last_name">Last Name</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col m6 s12">
                            <input id="phone" type="Text" class="validate" required>
                            <label for="phone">Phone</label>
                        </div>
                        <div class="input-field col m6 s12">
                            <input id="email" type="email" class="validate" required>
                            <label for="email">Email</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                          <textarea id="message" class="materialize-textarea"></textarea>
                          <label for="message">Message</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col m12">
                         <p class="right-align"><button class="btn btn-large waves-effect waves-light" type="button" name="action">Send Message</button></p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/footer.html
  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Company Bio</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project like it's our full time job.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Settings</h5>
          <ul>
            <li><a class="white-text" href="#!">Link 1</a></li>
            <li><a class="white-text" href="#!">Link 2</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Copyright © 2016 Library - made by REV
      </div>
    </div>
  </footer>

templates/form.html
{% extends "base.html" %} {% load material_form %}
{% block content %}
<div class='container'>
    <h1>{{ title }}</h1>
    <hr/>
    <form method='POST' action='' enctype='multipart/form-data'>
        {% csrf_token %} {% form form=form %} {% endform %}{% if form2 %} {{ form2 }} {% endif %}
        <input type='submit' class='btn btn-default' value='{{ title }}' />
    </form>
</div>
<br/> {% endblock content %}

templates/index.html
{% extends 'base.html' %} {% load staticfiles %} {% block content %}

<!-- Parallax 1 -->
<div id="index-banner" class="parallax-container">
    <div class="card green z-depth-2">
    {% if messages %}
        <div class="container card-content white-text">
            {% for message in messages %}
            <p{% if message.tags %} class="center-align {{ message.tags }}"{% endif %}>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
</div>
    <div class="section no-pad-bot">
        <div class="container">
            <br>
            <br>
            <h1 class="header center teal-text text-lighten-2">Welcome to Public library</h1>
            <div class="row center">
                <h5 class="header col s12 light">An online open book lending library</h5>
            </div>
            <div class="row center">
                <a href="{% url 'books:list' %}" id="download-button" class="btn-large waves-effect waves-light teal lighten-1">Look for Books</a>
            </div>
            <br>
            <br>
        </div>
    </div>
    <div class="parallax"><img src="{% static 'img/picture1.jpg' %}" alt="Unsplashed background img 1"></div>
</div>
<!-- end Parallax 1 -->
<div class="container">
    <div class="section">
        <!--   Icon Section   -->
        <div class="row">
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
                    <h5 class="center">Lorem ipsum dolor sit amet</h5>
                    <p class="light">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">group</i></h2>
                    <h5 class="center">Lorem ipsum dolor sit amet</h5>
                    <p class="light">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div>
            </div>
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
                    <h5 class="center">Lorem ipsum dolor sit amet</h5>
                    <p class="light">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Parallax 2 -->
<div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
        <div class="container">
            <div class="row center">
                <h5 class="header col s12 light">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</h5>
            </div>
        </div>
    </div>
    <div class="parallax"><img src="{% static 'img/background2.jpg' %}" alt="Unsplashed background img 2">
    </div>
</div>
<!-- end Parallax 2 -->
<div class="container">
    <!-- work time -->
    <div class="row">
        <div class="col s12">
            <h2 class="page-header">Library Work Hours:</h2>
        </div>
        <div class="col s6">
            <p>Library is open 6 days a week:</p>
            <ul>
                <li><strong>Monday</strong>: 7:00 am -- 18:00 pm</li>
                <li><strong>Tuesday</strong>: 7:00 am -- 18:00 pm</li>
                <li><strong>Wednesday</strong>: 7:00 am -- 18:00 pm</li>
                <li><strong>Thursday</strong>: 7:00 am -- 18:00 pm</li>
                <li><strong>Friday</strong>: 7:00 am -- 16:00 pm</li>
                <li><strong>Saturday</strong>: 7:00 am -- 14:00 pm</li>
            </ul>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.</p>
        </div>
        <div class="col s6">
            <img class="responsive-img" src="http://placehold.it/700x450" alt="picture">
        </div>
    </div>
    <!-- /.row -->
    <!-- new books -->
    <div class="row">
        <div class="col s12">
            <h2 class="page-header">New Books</h2>
        </div>
        <div class="col s12 m4">
            <div class="card hoverable">
                <div class="card-image">
                    <img class="responsive-img" src="http://placehold.it/600x650" alt="picture">
                    <span class="card-title">Card Title</span>
                </div>
                <div class="card-content">
                    <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
        <div class="col s12 m4">
            <div class="card hoverable">
                <div class="card-image">
                    <img class="responsive-img" src="http://placehold.it/600x650" alt="picture">
                    <span class="card-title">Card Title</span>
                </div>
                <div class="card-content">
                    <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
        <div class="col s12 m4">
            <div class="card hoverable">
                <div class="card-image">
                    <img class="responsive-img" src="http://placehold.it/600x650" alt="picture">
                    <span class="card-title">Card Title</span>
                </div>
                <div class="card-content">
                    <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
                </div>
                <div class="card-action">
                    <a href="#">This is a link</a>
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
</div>
{% endblock %}

templates/navbar.html
<div class="navbar-fixed">
<nav class="white" role="navigation">
  <div class="nav-wrapper container">
    <a id="logo-container" href="{% url 'index' %}" class="brand-logo">Library</a>
    <ul class="right hide-on-med-and-down">
      {% if user.is_staff or request.user.is_superuser %}
      <li><a href="{% url 'staff:homepage' %}">dashboard</a></li>
      {% endif %}
      <li>
        <a href="{% url 'books:list' %}">Books</a>
      </li>
      <li>
        <a href="{% url 'books:suggestbook' %}">Suggest a Book</a>
      </li>
      <li>
        <a href="{% url 'contact' %}">Contact</a>
      </li>
      <!-- Dropdown Trigger -->
      <li>
        <a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="material-icons nav-icon left">perm_identity</i><i class="material-icons nav-icon right">arrow_drop_down</i></a>
      </li>
    </ul>
    <ul id="nav-mobile" class="side-nav">
      {% if user.is_staff or request.user.is_superuser %}
      <li><a href="{% url 'staff:homepage' %}">dashboard</a></li>
      {% endif %}
      <li>
        <a href="{% url 'books:list' %}">Books</a>
      </li>
      <li>
        <a href="{% url 'books:suggestbook' %}">Suggest a Book</a>
      </li>
      <li>
        <a href="{% url 'contact' %}">Contact</a>
      </li>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content">
  {% if not user.is_authenticated %}
  <li>
    <a href="{% url 'login' %}">Login</a>
  </li>
  <li>
    <a href="{% url 'register' %}">Register</a>
  </li>
  {% else %}
  <li>
    <a href="{% url 'users:profile' request.user.pk %}">Profile</a>
  </li>
  {% endif %}
  {% if user.is_authenticated %}
  <li>
    <a href="{% url 'logout' %}">Logout</a>
  </li>
  {% endif %}
  
</ul>
</ul>
</div>

templates/no_access.html
{% extends 'base.html' %}

{% block content %}

		<div class="container jumbotron">
		  <h1 class="center-align">Access Denied!</h1>
		  	<p class="center-align">you dont have permission to view this page</p>
		</div>

{% endblock %}

templates/sidebar.html
        
<div class="col s3">
  <p class="lead">Search</p>
  <form action="">
    <div class="input-group">
      <input type="text" name="q" class="form-control" placeholder="Search for..." value="{{ request.GET.q }}">
      <span class="input-group-btn">
        <button class="btn btn-default" type="submite">Go!</button>
      </span>
    </div>
  </form>
  <p class="lead">Categories</p>
  <div class="collection">
    {% for tag in tags %}
    <a href="#" class="collection-item">{{tag.name}}</a>
    {% endfor %}
  </div>
</div>